@baseURL = http://localhost:3001

### Get Posts 
GET {{baseURL}}/api/blogs

### Create Post
POST {{baseURL}}/api/blogs
Content-Type: application/json

{
  "title": "Um titulo3",
  "author": "Um autor3",
  "url": "Uma url3",
  "likes": 2
}